const PRODUCTS = [
    {
        id: 0,
        name: 'Product',
        image: require('./images/sweater/sweater1.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'top',
        featured: false,
        amount:10,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 1,
        name: 'Product',
        image: require('./images/sweater/sweater2.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'top',
        featured: true,
        amount:15,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 2,
        name: 'Product',
        image: require('./images/sweater/sweater3.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'middle',
        featured: false,
        amount:18,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 3,
        name: 'Product',
        image: require('./images/sweater/sweater4.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'last',
        featured: true,
        amount:12,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 4,
        name: 'Product',
        image: require('./images/sweater/sweater5.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'last',
        featured: false,
        amount:11,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 5,
        name: 'Product',
        image: require('./images/sweater/sweater6.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'middle',
        featured: false,
        amount:1,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 6,
        name: 'Product',
        image: require('./images/suit/suit1.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'middle',
        featured: false,
        amount:10,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 7,
        name: 'Product',
        image: require('./images/suit/suit2.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'last',
        featured: false,
        amount:35,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 8,
        name: 'Product',
        image: require('./images/suit/suit3.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'last',
        featured: true,
        amount:40,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 9,
        name: 'Product',
        image: require('./images/suit/suit4.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'middle',
        featured: false,
        amount:54,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 10,
        name: 'Product',
        image: require('./images/suit/suit5.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'top',
        featured: false,
        amount:21,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 11,
        name: 'Product',
        image: require('./images/hoodie/hoodie1.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'last',
        featured: true,
        amount:86,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 12,
        name: 'Product',
        image: require('./images/hoodie/hoodie2.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'last',
        featured: true,
        amount:45,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 13,
        name: 'Product',
        image: require('./images/hoodie/hoodie3.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'middle',
        featured: false,
        amount:23,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 14,
        name: 'Product',
        image: require('./images/hoodie/hoodie4.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'middle',
        featured: false,
        amount:98,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 15,
        name: 'Product',
        image: require('./images/shirt/shirt1.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'middle',
        featured: false,
        amount:78,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 16,
        name: 'Product',
        image: require('./images/shirt/shirt2.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'last',
        featured: true,
        amount:87,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 17,
        name: 'Product',
        image: require('./images/shirt/shirt3.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'top',
        featured: false,
        amount:65,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 18,
        name: 'Product',
        image: require('./images/shirt/shirt4.jpg').default,
        category: 'clothes',
        new: false,
        ranking: 'last',
        featured: false,
        amount:54,
        hot: false,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 19,
        name: 'Product',
        image: require('./images/shirt/shirt5.jpg').default,
        category: 'clothes',
        new: true,
        ranking: 'last',
        featured: true,
        amount:76,
        hot: true,
        size: {
            xs: 'XS',
            s: 'S',
            m: 'M',
            l: 'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 20,
        name: 'Product',
        image: require('./images/vegetables/vegetables1.jpg').default,
        category: 'organic',
        new: true,
        ranking: 'top',
        featured: false,
        amount:45,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 21,
        name: 'Product',
        image: require('./images/vegetables/vegetables2.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'middle',
        featured: true,
        amount:28,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 22,
        name: 'Product',
        image: require('./images/vegetables/vegetables3.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'middle',
        featured: false,
        amount:87,
        hot: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 23,
        name: 'Product',
        image: require('./images/vegetables/vegetables4.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'last',
        featured: false,
        amount:56,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 24,
        name: 'Product',
        image: require('./images/vegetables/vegetables5.jpg').default,
        category: 'organic',
        new: true,
        ranking: 'middle',
        featured: true,
        amount:76,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 25,
        name: 'Product',
        image: require('./images/vegetables/vegetables6.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'last',
        featured: false,
        amount:7,
        hot: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 26,
        name: 'Product',
        image: require('./images/vegetables/vegetables7.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'top',
        featured: true,
        amount:81,
        hot: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 27,
        name: 'Product',
        image: require('./images/fruit/fruit1.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'last',
        featured: true,
        amount:53,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 28,
        name: 'Product',
        image: require('./images/fruit/fruit2.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'last',
        featured: true,
        amount:31,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 29,
        name: 'Product',
        image: require('./images/fruit/fruit3.jpg').default,
        category: 'organic',
        new: true,
        ranking: 'middle',
        featured: true,
        amount:49,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 30,
        name: 'Product',
        image: require('./images/fruit/fruit4.jpg').default,
        category: 'organic',
        new: false,
        ranking: 'top',
        featured: false,
        amount:90,
        hot: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 31,
        name: 'Product',
        image: require('./images/fruit/fruit5.jpg').default,
        category: 'organic',
        new: true,
        ranking: 'last',
        featured: false,
        amount:23,
        hot: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    },
    {
        id: 32,
        name: 'Product',
        image: require('./images/fruit/fruit6.jpg').default,
        category: 'organic',
        new: true,
        ranking: 'top',
        featured: true,
        amount:76,
        hot: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco."
    }
];

export default PRODUCTS;